

name: Anand_test


on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:  demo
    runs-on: ubuntu-latest
    
    steps:     
      - uses: actions/checkout@v2
    
      - name: Install NPM
        run: npm install
        
      - name: testing
        run: mkdir test
