

name: Anand_test


on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:  
    runs-on: samplerunner
    
    steps:     
      - uses: actions/checkout@v2
    
      - name: Install NPM
        run: npm install
